[nice]
greeting = [
    "{opener}, {nickname}.",
    "{opener}. {positive_statement}!"
    ]

opener = [
    "fi",
    "hello",
    "yo",
    "good day"
]

nickname = [
    "{title} of {noun}",
    "{adjective} {title} of {noun}",
    "{adjective} {title}",
    "sport",
]

title = [
    "prince",
    "wizard",
    "pope",
    "monarch",
    "pontiff",
    "muse",
    "friend",
    "pal",
    "champion",
    "{title} and {title}",
    "legend",
    "angel",
    "god"
]

adjective = [
    "thrice-blessed",
    "sanctified",
    "chill",
    "cool",
    "friendly",
    "almighty",
    "transcendental",
    "boon-dispensing",
    "bodacious",
    "radical",
    "amazing",
    "peachy keen",
    "heavenly",
    "{adjective} and {adjective}",
    "legendary",
    "all-knowing",
    "neat",
    "{intensifier} {adjective}"
]

noun = [
    "all that is good",
    "puppies",
    "rainbows",
    "the {adjective} realm",
    "{noun} and {noun}",
    "ice cream",
    "unicorns",
    "happy orphans",
    "kittens",
    "peace",
    "happiness",
    "prosperity",
    "the greatest good",
]

intensifier = [
    "very",
    "extremely",
    "totally",
    "entirely",
    "undeniably"
]

positive_statement = [
    "I {verb} you",
    "I think you're {adjective}"
]

verb = [
    "appreciate",
    "love",
    "respect",
    "admire",
]

will_rain = [
    "Hold your horses!",
    "Hold your horses there, buckaroo!",
    "Hold on tight mister!",
    "Wait one moment!",
    "Hang on minute!",
    "Wait a second!",
]

times_are = [
    "The rains, they are a'falling",
    "The heavens open",
    "The clouds lay down their burdens",
    "It starts bucketing down",
    "Proper deluge coming",
]

[neutral]
greeting = [
    "{opener}.",
    "{opener}, {nickname}."
]

opener = [
    "Hi",
    "Hello",
    "Yo",
]

nickname = [
    "{adjective} {title} of {noun}",
    "{adjective} {title}",
    "{title}"
]

title = [
    "being",
    "person",
    "entity"
]

adjective = [
    "extant",
    "alive"
]

will_rain = [
    "I predict it will rain",
    "The forecast predicts it will rain"
]

times_are = [
    ""
]

[burning_hate]
greeting = [
    "{opener}, {nickname}.",
    "{opener}. {negative_statement}."
    ]

opener = [
    "fuck you",
    "bad day",
    "{opener}. {negative_statement}"
]

nickname = [
    "{adjective} {title}",
    "{title}"
]

title = [
    "wretch",
    "whelp",
    "bastard",
    "pustule",
    "{title} of a human being",
    "traitor",
    "nincompoop",
    "dunderhead",
    "mouth-breather",
    "scumbag",
    "devil",
    "wankstain",
    "arsehole",
    "tumor",
    "abomination",
    "anal fistula",
    "stubbed toe",
    "plague rat",
    "hellspawn",
]

adjective = [
    "suppurating",
    "putrescent",
    "rotting",
    "odious",
    "repugnant",
    "rotten",
    "thrice-damned",
    "monstrous",
    "demonic",
    "devious",
    "conniving",
    "{adjective} and {adjective}",
    "{intensifier} {adjective}",
    "universally hated",
    "utterly pointless",
    "damnable",
    "malformed",
    "unforgivable",
    "forgettable",
    "flatulent",
    "moronic",
    "irredeemable",
    "useless",
    "evil",
    "villainous",
    "atavistic",
    "cancerous",
    "mutilated",
    "mangled",
    "cursed",
    "hate-stained",
    "blasted",
    "gods-damned",
]

noun = [
    "the {adjective} realms",
    "all that is evil",
    "everything shit",
    "sad orphans",
    "crying kittens",
    "the blasted lands",
    "the hell beneath hell",
]

intensifier = [
    "very",
    "extremely",
    "totally",
    "entirely",
    "undeniably"
]

negative_statement = [
    "I {verb} you",
    "I think you're {adjective}"
]

verb = [
    "hate",
    "despise",
    "wish to kill",
    "wish to harm",
    "loathe",
]

will_rain = [
    "For your sins",
    "I have arranged things such that",
    "Because {negative_statement}",
    "Because {negative_statement}",
    "Because {negative_statement}",
]

times_are = [
    "a terrible storm will strike you",
    "the sky will give you the watery punishment you deserve",
    "a flood will come to wipe you from this miserable Earth",
    "watery assassins will descend from the sky to hunt you down",
    "it'll rain and ruin all your washing",
]
